FROM scratch
ARG GIT_SHA
ARG WORKFLOW_RELEASE
ENV GIT_SHA=$GIT_SHA
ENV WORKFLOW_RELEASE=$WORKFLOW_RELEASE
ENV POWERED_BY=Jenkins-X
EXPOSE 8080
ENTRYPOINT ["/croc-hunter-jenkinsx"]
COPY ./bin/ /
COPY static/ static/
