apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker:
      buildArgs:
        GIT_SHA: ''
        WORKFLOW_RELEASE: '1'
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/carlossg/croc-hunter-jenkinsx:'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/carlossg/croc-hunter-jenkinsx'
    local: {}
  deploy:
    helm:
      releases:
      - name: croc-hunter-jenkinsx
        chartPath: charts/croc-hunter-jenkinsx
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/carlossg/croc-hunter-jenkinsx'
          image.tag: '{{.TAG}}'
