apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker:
      buildArgs:
        GIT_SHA: "{{.GIT_COMMIT}}"
        WORKFLOW_RELEASE: "{{.VERSION}}"
  local: {}
deploy:
  kubectl:
    manifests:
